# Setup
title: some assembly required
tagline: "look mom no javascript"
url: https://getpoole.com
paginate: 1
baseurl: "/fungible"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Martin Roberts
  url: https://twitter.com/dokoissho
  email: dokoissho@sdf.org

# Custom vars
version: 3.0.0
